package match

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

//go:embed cfgs/*.cfg
var defaultCfgs embed.FS

// Files the agent writes into each match cfg dir.
const (
	ServerCfgName = "server.cfg"
	MatchJSONName = "match.json"
)

// Params is everything needed to render one match.
type Params struct {
	Req        StartRequest
	Spec       ModeSpec
	Port       int
	TVPort     int
	TVPassword string
	// CfgRel is the match dir relative to game/csgo/cfg, with forward slashes.
	CfgRel string
	// ModeCfgDir overrides the embedded mode cfgs when it holds a file named Spec.ExecCfg.
	ModeCfgDir string
}

// MaxPlayers is both teams plus one spare slot.
func MaxPlayers(spec ModeSpec) int { return spec.TeamSize*2 + 1 }

// LaunchArgs builds the cs2 argument list. Order matters: game_type and game_mode go before the map.
func LaunchArgs(p Params) ([]string, error) {
	if !p.Spec.Configured() {
		return nil, ErrModeNotConfigured
	}
	args := []string{
		"-dedicated",
		"-console",
		"-port", strconv.Itoa(p.Port),
		"-maxplayers", strconv.Itoa(MaxPlayers(p.Spec)),
		"+tv_port", strconv.Itoa(p.TVPort),
		"+tv_enable", "1",
		"+bot_quota", "0",
		"+game_type", strconv.Itoa(*p.Spec.GameType),
		"+game_mode", strconv.Itoa(*p.Spec.GameMode),
	}
	args = append(args, p.Spec.ExtraArgs...)
	if p.Req.Map.WorkshopID != "" {
		args = append(args, "+host_workshop_map", p.Req.Map.WorkshopID)
	} else {
		name, err := LevelName(p.Req.Map)
		if err != nil {
			return nil, err
		}
		args = append(args, "+map", name)
	}
	args = append(args,
		"+sv_setsteamaccount", p.Req.GSLT,
		"+sv_password", p.Req.Password,
		"+exec", p.CfgRel+"/"+ServerCfgName,
	)
	return args, nil
}

// ServerCfg renders server.cfg. It ends by exec'ing the mode cfg from the same dir.
func ServerCfg(p Params) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	short := p.Req.MatchID
	if len(short) > 8 {
		short = short[:8]
	}
	w("// Generated by rushsite-agent for match %s. Do not edit.", p.Req.MatchID)
	w(`hostname "rushsite %s"`, short)
	w(`sv_password "%s"`, p.Req.Password)
	w(`rcon_password ""`)
	w("sv_lan 0")
	w("sv_hibernate_when_empty 0")
	w("sv_allow_votes 0")
	w("bot_quota 0")
	w("bot_kick")
	w("tv_enable 1")
	w("tv_port %d", p.TVPort)
	w(`tv_password "%s"`, p.TVPassword)
	w("tv_autorecord 0")
	if len(p.Req.Teams) == 2 {
		w(`mp_teamname_1 "%s"`, CfgString(p.Req.Teams[0].Label()))
		w(`mp_teamname_2 "%s"`, CfgString(p.Req.Teams[1].Label()))
	}
	w("exec %s/%s", p.CfgRel, p.Spec.ExecCfg)
	return b.String()
}

// ModeCfg returns the mode exec cfg, from ModeCfgDir if present or else the embedded default.
func ModeCfg(p Params) ([]byte, error) {
	name := p.Spec.ExecCfg
	if !reCfgName.MatchString(name) {
		return nil, fmt.Errorf("bad execCfg name %q", name)
	}
	if p.ModeCfgDir != "" {
		b, err := os.ReadFile(filepath.Join(p.ModeCfgDir, name))
		if err == nil {
			return b, nil
		}
		if !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
	}
	b, err := defaultCfgs.ReadFile("cfgs/" + name)
	if err != nil {
		return nil, invalid("no mode cfg named %s on this agent", name)
	}
	return b, nil
}

// PluginJSON renders match.json for the plugin.
func PluginJSON(p Params) ([]byte, error) {
	pc := PluginConfig{
		MatchID:         p.Req.MatchID,
		Mode:            p.Req.Mode,
		AllowedSteamIDs: p.Req.AllowedSteamIDs,
		Teams:           p.Req.Teams,
		Password:        p.Req.Password,
		WebhookURL:      p.Req.WebhookURL,
		WebhookSecret:   p.Req.WebhookSecret,
		DemoUpload:      p.Req.DemoUpload,
		WinCondition:    p.Spec.WinCondition,
	}
	return json.MarshalIndent(pc, "", "  ")
}

// RenderFiles returns every file for the match dir keyed by file name.
func RenderFiles(p Params) (map[string][]byte, error) {
	mode, err := ModeCfg(p)
	if err != nil {
		return nil, err
	}
	js, err := PluginJSON(p)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		ServerCfgName:  []byte(ServerCfg(p)),
		p.Spec.ExecCfg: mode,
		MatchJSONName:  js,
	}, nil
}

// WriteDir creates dir fresh and writes files into it.
func WriteDir(dir string, files map[string][]byte) error {
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0o600); err != nil {
			return err
		}
	}
	return nil
}

// Connect is the string players paste into the console.
func Connect(ip string, port int, password string) string {
	return fmt.Sprintf("connect %s:%d; password %s", ip, port, password)
}
