package match

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

//go:embed cfgs/*.cfg
var defaultCfgs embed.FS

// Files the agent writes into each match cfg dir.
// ModeCfgName holds the mode settings. The plugin execs it again at match start
// because Valve's gamemode cfg runs on map load after the command line.
const (
	ServerCfgName = "server.cfg"
	ModeCfgName   = "mode.cfg"
	MatchJSONName = "match.json"
)

// Params is everything needed to render one match.
type Params struct {
	Req        StartRequest
	Spec       ModeSpec
	Port       int
	TVPort     int
	TVPassword string
	// CfgRel is the match dir relative to game/csgo/cfg, with forward slashes.
	CfgRel string
	// ModeCfgDir overrides the embedded mode cfgs when it holds a file named Spec.ExecCfg.
	ModeCfgDir string
}

// MaxPlayers is both teams plus one spare slot.
func MaxPlayers(spec ModeSpec) int { return spec.TeamSize*2 + 1 }

// LaunchArgs builds the cs2 argument list. Order matters: game_type and game_mode go before the map.
// server.cfg and then mode.cfg are exec'd last.
func LaunchArgs(p Params) ([]string, error) {
	args := []string{
		"-dedicated",
		"-console",
		"-port", strconv.Itoa(p.Port),
		"-maxplayers", strconv.Itoa(MaxPlayers(p.Spec)),
		"+tv_port", strconv.Itoa(p.TVPort),
		"+tv_enable", "1",
		"+bot_quota", "0",
		"+game_type", strconv.Itoa(p.Spec.GameType),
		"+game_mode", strconv.Itoa(p.Spec.GameMode),
	}
	args = append(args, p.Spec.ExtraArgs...)
	switch {
	case p.Spec.WorkshopID != "":
		args = append(args, "+host_workshop_map", p.Spec.WorkshopID)
	case reMapName.MatchString(p.Spec.MapName):
		args = append(args, "+map", p.Spec.MapName)
	default:
		return nil, invalid("launch has no valid map")
	}
	args = append(args,
		"+sv_setsteamaccount", p.Req.GSLT,
		"+sv_password", p.Req.Password,
		"+exec", p.CfgRel+"/"+ServerCfgName,
		"+exec", ModeCfgPath(p.CfgRel),
	)
	return args, nil
}

// ModeCfgPath is the exec path of the match's mode.cfg, relative to game/csgo/cfg.
func ModeCfgPath(cfgRel string) string { return cfgRel + "/" + ModeCfgName }

// ServerCfg renders server.cfg. The mode settings live in mode.cfg.
func ServerCfg(p Params) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	short := p.Req.MatchID
	if len(short) > 8 {
		short = short[:8]
	}
	w("// Generated by rushsite-agent for match %s. Do not edit.", p.Req.MatchID)
	w(`hostname "rushsite %s"`, short)
	w(`sv_password "%s"`, p.Req.Password)
	w(`rcon_password ""`)
	w("sv_lan 0")
	w("sv_hibernate_when_empty 0")
	w("sv_allow_votes 0")
	w("bot_quota 0")
	w("bot_kick")
	w("tv_enable 1")
	w("tv_port %d", p.TVPort)
	w(`tv_password "%s"`, p.TVPassword)
	w("tv_autorecord 0")
	if len(p.Req.Teams) == 2 {
		w(`mp_teamname_1 "%s"`, CfgString(p.Req.Teams[0].Label()))
		w(`mp_teamname_2 "%s"`, CfgString(p.Req.Teams[1].Label()))
	}
	return b.String()
}

// modeCfgSource reads a shipped mode cfg, from dir if present or else the embedded default.
func modeCfgSource(name, dir string) ([]byte, error) {
	if !reCfgName.MatchString(name) {
		return nil, invalid("bad execCfg name %q", name)
	}
	if dir != "" {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err == nil {
			return b, nil
		}
		if !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
	}
	b, err := defaultCfgs.ReadFile("cfgs/" + name)
	if err != nil {
		return nil, invalid("no mode cfg named %s on this agent", name)
	}
	return b, nil
}

// HasModeCfg reports whether the agent can exec the named mode cfg.
func HasModeCfg(name, dir string) bool {
	_, err := modeCfgSource(name, dir)
	return err == nil
}

// EmbeddedCfgs lists the mode cfgs built into the agent.
func EmbeddedCfgs() []string {
	entries, _ := fs.ReadDir(defaultCfgs, "cfgs")
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	return names
}

// ModeCfg returns the match's mode.cfg: the shipped cfg named by Spec.ExecCfg under a header.
func ModeCfg(p Params) ([]byte, error) {
	src, err := modeCfgSource(p.Spec.ExecCfg, p.ModeCfgDir)
	if err != nil {
		return nil, err
	}
	head := fmt.Sprintf("// Generated by rushsite-agent for match %s from %s. Do not edit.\n", p.Req.MatchID, p.Spec.ExecCfg)
	return append([]byte(head), src...), nil
}

// PluginJSON renders match.json for the plugin.
func PluginJSON(p Params) ([]byte, error) {
	pc := PluginConfig{
		MatchID:         p.Req.MatchID,
		Mode:            p.Req.Mode,
		AllowedSteamIDs: p.Req.AllowedSteamIDs,
		Teams:           p.Req.Teams,
		Password:        p.Req.Password,
		WebhookURL:      p.Req.WebhookURL,
		WebhookSecret:   p.Req.WebhookSecret,
		DemoUpload:      p.Req.DemoUpload,
		WinCondition:    p.Spec.WinCondition,
	}
	return json.MarshalIndent(pc, "", "  ")
}

// RenderFiles returns every file for the match dir keyed by file name.
func RenderFiles(p Params) (map[string][]byte, error) {
	mode, err := ModeCfg(p)
	if err != nil {
		return nil, err
	}
	js, err := PluginJSON(p)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		ServerCfgName: []byte(ServerCfg(p)),
		ModeCfgName:   mode,
		MatchJSONName: js,
	}, nil
}

// WriteDir creates dir fresh and writes files into it.
func WriteDir(dir string, files map[string][]byte) error {
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0o600); err != nil {
			return err
		}
	}
	return nil
}

// Connect is the string players paste into the console.
func Connect(ip string, port int, password string) string {
	return fmt.Sprintf("connect %s:%d; password %s", ip, port, password)
}
